services:

  db:
    build:
      context: database
    container_name: vdm_db
    volumes:
      - vdm_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -h db -p 5432 -d vdm_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  frontend:
#   build:
#     context: frontend/vigie-du-mensonge
#   container_name: vdm_frontend
#   ports:
#      - "5173:8080"

  backend:
    build:
      context: backend
    container_name: vdm_backend
    ports:
      - "8080:8080"
    env_file:
      - .backend.env
    depends_on:
      db:
        condition: service_healthy

#  data_import:
#    build:
#      context: data_import
#    container_name: vdm_data_import
#    restart: no
#    env_file:
#      - .backend.env # Réutilise la configuration de la DB
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  vdm_pg_data:
