// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID          uuid.UUID `db:"id" json:"id"`
	RedactorID  uuid.UUID `db:"redactor_id" json:"redactor_id"`
	ModeratorID uuid.UUID `db:"moderator_id" json:"moderator_id"`
	Status      string    `db:"status" json:"status"`
	Category    string    `db:"category" json:"category"`
	Title       string    `db:"title" json:"title"`
	Body        string    `db:"body" json:"body"`
	EventDate   time.Time `db:"event_date" json:"event_date"`
	Reference   uuid.UUID `db:"reference" json:"reference"`
	Major       int16     `db:"major" json:"major"`
	Minor       int16     `db:"minor" json:"minor"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt   time.Time `db:"deleted_at" json:"deleted_at"`
}

type ArticlePolitician struct {
	ArticleID    uuid.UUID `db:"article_id" json:"article_id"`
	PoliticianID uuid.UUID `db:"politician_id" json:"politician_id"`
}

type ArticleReview struct {
	ID          uuid.UUID `db:"id" json:"id"`
	ArticleID   uuid.UUID `db:"article_id" json:"article_id"`
	ModeratorID uuid.UUID `db:"moderator_id" json:"moderator_id"`
	Decision    string    `db:"decision" json:"decision"`
	Notes       string    `db:"notes" json:"notes"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt   time.Time `db:"deleted_at" json:"deleted_at"`
}

type ArticleSource struct {
	ArticleID uuid.UUID `db:"article_id" json:"article_id"`
	Url       string    `db:"url" json:"url"`
}

type ArticleTag struct {
	ArticleID uuid.UUID `db:"article_id" json:"article_id"`
	Tag       string    `db:"tag" json:"tag"`
}

type Government struct {
	ID              uuid.UUID `db:"id" json:"id"`
	PrimeMinisterID uuid.UUID `db:"prime_minister_id" json:"prime_minister_id"`
	Reference       int16     `db:"reference" json:"reference"`
	StartDate       time.Time `db:"start_date" json:"start_date"`
	EndDate         time.Time `db:"end_date" json:"end_date"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt       time.Time `db:"deleted_at" json:"deleted_at"`
}

type Occupation struct {
	ID                    uuid.UUID `db:"id" json:"id"`
	PoliticianID          uuid.UUID `db:"politician_id" json:"politician_id"`
	GovernmentID          uuid.UUID `db:"government_id" json:"government_id"`
	PresidentialReference *int16    `db:"presidential_reference" json:"presidential_reference"`
	Code                  string    `db:"code" json:"code"`
	Title                 string    `db:"title" json:"title"`
	StartDate             time.Time `db:"start_date" json:"start_date"`
	EndDate               time.Time `db:"end_date" json:"end_date"`
	CreatedAt             time.Time `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt             time.Time `db:"deleted_at" json:"deleted_at"`
}

type Politician struct {
	ID        uuid.UUID `db:"id" json:"id"`
	LastName  string    `db:"last_name" json:"last_name"`
	FirstName string    `db:"first_name" json:"first_name"`
	ImageUrl  *string   `db:"image_url" json:"image_url"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time `db:"deleted_at" json:"deleted_at"`
}

type Role struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt time.Time `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Tag       string    `db:"tag" json:"tag"`
	Email     string    `db:"email" json:"email"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}

type UserToken struct {
	ID       uuid.UUID `db:"id" json:"id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Category string    `db:"category" json:"category"`
	Hash     string    `db:"hash" json:"hash"`
	Expiry   time.Time `db:"expiry" json:"expiry"`
}
