apiVersion: v1
kind: LimitRange
metadata:
  name: vdm-defaults
  namespace: vdm
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "75m"
        memory: "96Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "25m"
        memory: "32Mi"