parameters:
  ArticleId:
    name: articleId
    in: path
    required: true
    schema: { type: string, format: uuid }
  RoleId:
    name: roleId
    in: path
    required: true
    schema: { type: string }
  PoliticianIdQuery:
    name: politicianId
    in: query
    required: false
    schema: { type: string, format: uuid }
  EmailQuery:
    name: email
    in: query
    required: true
    schema: { type: string, format: email }
  BeforeQuery:
    name: before
    in: query
    required: true
    schema: { type: string, format: date-time }
  StatusQuery:
    name: status
    in: query
    required: false
    schema:
      type: array
      items: { $ref: "./schemas.yml#/schemas/ArticleStatus" }
      style: form
      explode: true
  CategoriesQuery:
    name: categories
    in: query
    required: false
    schema:
      type: array
      items: { $ref: "./schemas.yml#/schemas/ArticleCategory" }
      style: form
      explode: true