apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vdm
  name: data-import
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: data-import
  template:
    metadata:
      labels:
        app: data-import
    spec:
      serviceAccountName: vdm-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: { } # ephemeral, node storage
      containers:
        - name: backend
          image: geo1796/vdm-data_import@sha256:54ce89cc7fd1d395f808b86ef1fa975ce9600b69b071e85bddcc2dac7f648ec0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PORT
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_SSL_MODE