name: Go CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: |
            backend/go.sum

            - name: Download dependencies
              working-directory: ./backend
              run: go mod download

            - name: Run tests
              working-directory: ./backend
              run: go test ./... -v
